name: onlishop-version
description: "Returns the Onlishop version matching the current branch or a fallback"
author: "Lyric Song"
branding:
  color: "blue"
  icon: "download"

inputs:
  fallback:
    description: Fallback version if no match is found
    default: trunk
    required: false
  repo:
    description: GitHub repository to check branches
    default: onlishop/onlishop
    required: false
  ref:
    description: Git reference to match (defaults to github.ref)
    required: false
    default: ""
  base-ref:
    description: Base ref for pull requests (defaults to github.base_ref)
    required: false
    default: ""
  head-ref:
    description: Head ref for pull requests (defaults to github.head_ref)
    required: false
    default: ""
  github-token:
    description: Token for accessing GitHub API
    required: false
    default: ""

outputs:
  onlishop-version:
    description: The matching Onlishop version or fallback

runs:
  using: "node22"
  main: "dist/main/index.js"
